import type { Metadata } from "next";
import "./globals.css";
import { quicksand } from "@/font";
import { Toaster } from "sonner";
import { Providers } from "./provider";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={cn(
          "mx-auto min-h-dvh  w-full antialised ",
          quicksand.className
        )}
      >
        <Providers>
          {children}
          <Toaster position="top-right" richColors />
        </Providers>
      </body>
    </html>
  );
}
